name: do_more
description: A good lookig glorified todo list.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cloud_firestore: ^0.9.0
  cupertino_icons: ^0.1.2
  firebase_analytics: ^2.0.2
  firebase_auth: ^0.8.1
  firebase_core: ^0.3.0
  firebase_ml_vision: ^0.6.0
  firebase_storage: ^2.0.1
  flare_flutter: ^1.3.2
  font_awesome_flutter: ^8.4.0
  google_sign_in: ^4.0.1+1
  http: ^0.12.0
  image_picker: ^0.5.0+3
  mockito: ^4.0.0
  path_provider: ^0.5.0+1
  photo_view: 0.2.3
  rxdart: ^0.20.0
  sqflite: ^1.1.0
  uuid: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/animations/loading_logo.flr
    - assets/animations/loading_animation_looped.flr
    - assets/animations/loading_animation.flr

  fonts:
    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

